// ─── I18N ────────────────────────────────────────────────────
var LEG={
  de:"Diese App (WIPULSCAN PRO) wird von Cobra Dynamics, Dennis Stein & Christoph Frick, Nördliche Ringstraße 75, 63225 Langen betrieben.\n\nDie App liest ausschließlich Gerätedaten via Web-APIs. Keine personenbezogenen Daten erhoben, gespeichert oder übermittelt.\n\nRechtsgrundlage: DSGVO Art. 6 Abs. 1 lit. b.\nKontakt: dennis.stein@cobradynamics.de",
  en:"This app (WIPULSCAN PRO) is operated by Cobra Dynamics, Dennis Stein & Christoph Frick, Langen, Germany.\n\nThe app reads device data only via Web APIs. No personal data is collected, stored or transmitted.\n\nLegal basis: GDPR Art. 6(1)(b). Contact: dennis.stein@cobradynamics.de",
  zh:"本应用由 Cobra Dynamics 运营。不收集任何个人数据。联系：dennis.stein@cobradynamics.de",
  es:"Esta app es operada por Cobra Dynamics, Langen, Alemania. Solo lee datos del dispositivo. No se recopilan datos personales.\nContacto: dennis.stein@cobradynamics.de",
  hi:"यह ऐप Cobra Dynamics द्वारा संचालित है। केवल डिवाइस डेटा पढ़ी जाती है। कोई व्यक्तिगत डेटा एकत्र नहीं किया जाता।\nसंपर्क: dennis.stein@cobradynamics.de",
  ar:"يُشغَّل هذا التطبيق من قِبَل Cobra Dynamics. لا تُجمع أي بيانات شخصية.\nالتواصل: dennis.stein@cobradynamics.de",
  pt:"Este app é operado pela Cobra Dynamics, Langen, Alemanha. Nenhum dado pessoal é coletado.\nContato: dennis.stein@cobradynamics.de",
  fr:"Cette application est gérée par Cobra Dynamics, Langen, Allemagne. Aucune donnée personnelle n'est collectée.\nContact: dennis.stein@cobradynamics.de",
  ru:"Приложение управляется Cobra Dynamics, Лангена, Германия. Личные данные не собираются.\nКонтакт: dennis.stein@cobradynamics.de",
  ja:"このアプリはCobra Dynamics（ドイツ）が運営します。個人データの収集は一切行いません。\n連絡先: dennis.stein@cobradynamics.de"
};
var LANGS={
  de:{tap_lbl:"· Tippen zum Starten ·",c_eye:"Bitte lies die Datenschutzerklärung",c_sub:"Diese App läuft vollständig lokal.<br>Keine Server. Keine Tracking-Daten.",c_chk:"Ich habe die Datenschutzerklärung gelesen und stimme zu.",c_ok:"Starten",s_title:"EINSTELLUNGEN",s_opt:"OPTIONEN",s_feat:"FEATURES",h_ready:"BEREIT",h_scan:"SCANNING",h_pause:"PAUSIERT",ml_sig:"SIGNAL",ml_dl:"DOWNLOAD",ml_rtt:"LATENZ",l_s:"STARK",l_g:"GUT",l_m:"MITTEL",l_w:"SCHWACH",btn_start:"Scan Starten",btn_stop:"Scan Stoppen",bd_current:"Aktuelle Verbindung",bd_main:"Echtdaten",bd_est:"Geschätzt",bd_stability:"STABILITÄT",feats:["Echtzeit via NetworkInformation API","Interaktive Netzwerk-Bubbles + AR","3.75s Cinematic Intro + Jingle","10 Sprachen verfügbar","DSGVO-konform · lokal only"],msgs:[{min:88,msg:"Exzellentes Signal — Glasfaser-Qualität"},{min:72,msg:"Starkes Signal — optimale Verbindung"},{min:50,msg:"Gutes Signal — stabil und zuverlässig"},{min:30,msg:"Mittleres Signal — ausreichend"},{min:12,msg:"Schwaches Signal — eingeschränkt"},{min:0,msg:"Kritisches Signal — Verbindung instabil"}]},
  en:{tap_lbl:"· Tap to Start ·",c_eye:"Please read the Privacy Policy",c_sub:"This app runs entirely locally.<br>No servers. No tracking.",c_chk:"I have read the Privacy Policy and agree.",c_ok:"Start",s_title:"SETTINGS",s_opt:"OPTIONS",s_feat:"FEATURES",h_ready:"READY",h_scan:"SCANNING",h_pause:"PAUSED",ml_sig:"SIGNAL",ml_dl:"DOWNLOAD",ml_rtt:"LATENCY",l_s:"STRONG",l_g:"GOOD",l_m:"MEDIUM",l_w:"WEAK",btn_start:"Start Scan",btn_stop:"Stop Scan",bd_current:"Active Connection",bd_main:"Real data",bd_est:"Estimated",bd_stability:"STABILITY",feats:["Real-time via NetworkInformation API","Interactive Network Bubbles + AR","3.75s Cinematic Intro + Jingle","10 languages available","GDPR-compliant · local only"],msgs:[{min:88,msg:"Excellent signal — fiber quality"},{min:72,msg:"Strong signal — optimal connection"},{min:50,msg:"Good signal — stable & reliable"},{min:30,msg:"Medium signal — adequate"},{min:12,msg:"Weak signal — limited reception"},{min:0,msg:"Critical signal — connection unstable"}]},
  zh:{tap_lbl:"· 点击开始 ·",c_eye:"请阅读隐私政策",c_sub:"本应用完全在本地运行。<br>无服务器。无追踪。",c_chk:"我已阅读并同意隐私政策。",c_ok:"开始",s_title:"设置",s_opt:"选项",s_feat:"功能说明",h_ready:"就绪",h_scan:"扫描中",h_pause:"已暂停",ml_sig:"信号",ml_dl:"下载",ml_rtt:"延迟",l_s:"强",l_g:"良",l_m:"中",l_w:"弱",btn_start:"开始扫描",btn_stop:"停止扫描",bd_current:"当前连接",bd_main:"真实数据",bd_est:"估算",bd_stability:"稳定性",feats:["实时 NetworkInformation API","交互式网络气泡 + AR","3.75秒电影级开场","10种语言","符合GDPR · 纯本地"],msgs:[{min:88,msg:"极佳信号 — 光纤级质量"},{min:72,msg:"强信号 — 最佳连接"},{min:50,msg:"良好信号 — 稳定可靠"},{min:30,msg:"中等信号 — 基本够用"},{min:12,msg:"弱信号 — 接收受限"},{min:0,msg:"极弱信号 — 连接不稳定"}]},
  es:{tap_lbl:"· Toca para Iniciar ·",c_eye:"Lee la política de privacidad",c_sub:"Esta app funciona completamente en local.<br>Sin servidores. Sin rastreo.",c_chk:"He leído la política de privacidad y acepto.",c_ok:"Iniciar",s_title:"AJUSTES",s_opt:"OPCIONES",s_feat:"FUNCIONES",h_ready:"LISTO",h_scan:"ESCANEANDO",h_pause:"PAUSADO",ml_sig:"SEÑAL",ml_dl:"DESCARGA",ml_rtt:"LATENCIA",l_s:"FUERTE",l_g:"BUENA",l_m:"MEDIA",l_w:"DÉBIL",btn_start:"Iniciar Escaneo",btn_stop:"Detener Escaneo",bd_current:"Conexión activa",bd_main:"Datos reales",bd_est:"Estimado",bd_stability:"ESTABILIDAD",feats:["Tiempo real via NetworkInformation API","Burbujas de red interactivas + AR","Intro cinemático 3.75s + jingle","10 idiomas disponibles","Conforme GDPR · solo local"],msgs:[{min:88,msg:"Señal excelente — calidad fibra"},{min:72,msg:"Señal fuerte — conexión óptima"},{min:50,msg:"Buena señal — estable y fiable"},{min:30,msg:"Señal media — suficiente"},{min:12,msg:"Señal débil — recepción limitada"},{min:0,msg:"Señal crítica — conexión inestable"}]},
  hi:{tap_lbl:"· शुरू करने के लिए टैप करें ·",c_eye:"कृपया गोपनीयता नीति पढ़ें",c_sub:"यह ऐप पूरी तरह स्थानीय रूप से चलती है।<br>कोई सर्वर नहीं। कोई ट्रैकिंग नहीं।",c_chk:"मैंने गोपनीयता नीति पढ़ी है और सहमत हूँ।",c_ok:"शुरू करें",s_title:"सेटिंग्स",s_opt:"विकल्प",s_feat:"सुविधाएँ",h_ready:"तैयार",h_scan:"स्कैनिंग",h_pause:"रुका हुआ",ml_sig:"सिग्नल",ml_dl:"डाउनलोड",ml_rtt:"विलंब",l_s:"मजबूत",l_g:"अच्छा",l_m:"मध्यम",l_w:"कमजोर",btn_start:"स्कैन शुरू",btn_stop:"स्कैन रोकें",bd_current:"सक्रिय कनेक्शन",bd_main:"वास्तविक डेटा",bd_est:"अनुमानित",bd_stability:"स्थिरता",feats:["NetworkInformation API रियलटाइम","इंटरैक्टिव नेटवर्क बबल + AR","3.75s सिनेमाई इंट्रो + जिंगल","10 भाषाएँ उपलब्ध","GDPR अनुपालन · केवल स्थानीय"],msgs:[{min:88,msg:"बेहतरीन सिग्नल — फाइबर गुणवत्ता"},{min:72,msg:"मजबूत सिग्नल — इष्टतम कनेक्शन"},{min:50,msg:"अच्छा सिग्नल — स्थिर और विश्वसनीय"},{min:30,msg:"मध्यम सिग्नल — पर्याप्त"},{min:12,msg:"कमजोर सिग्नल — सीमित रिसेप्शन"},{min:0,msg:"क्रिटिकल सिग्नल — कनेक्शन अस्थिर"}]},
  ar:{tap_lbl:"· انقر للبدء ·",c_eye:"يُرجى قراءة سياسة الخصوصية",c_sub:"يعمل هذا التطبيق محلياً بالكامل.<br>لا خوادم. لا تتبع.",c_chk:"لقد قرأت سياسة الخصوصية وأوافق عليها.",c_ok:"ابدأ",s_title:"الإعدادات",s_opt:"خيارات",s_feat:"الميزات",h_ready:"جاهز",h_scan:"جارٍ المسح",h_pause:"متوقف",ml_sig:"إشارة",ml_dl:"تحميل",ml_rtt:"استجابة",l_s:"قوية",l_g:"جيدة",l_m:"متوسطة",l_w:"ضعيفة",btn_start:"بدء المسح",btn_stop:"إيقاف المسح",bd_current:"الاتصال النشط",bd_main:"بيانات حقيقية",bd_est:"تقديري",bd_stability:"الاستقرار",feats:["مسح فوري عبر NetworkInformation API","فقاعات شبكة تفاعلية + AR","مقدمة سينمائية 3.75 ثانية","10 لغات متاحة","متوافق مع GDPR · محلي فقط"],msgs:[{min:88,msg:"إشارة ممتازة — جودة الألياف"},{min:72,msg:"إشارة قوية — اتصال مثالي"},{min:50,msg:"إشارة جيدة — مستقرة وموثوقة"},{min:30,msg:"إشارة متوسطة — كافية"},{min:12,msg:"إشارة ضعيفة — استقبال محدود"},{min:0,msg:"إشارة حرجة — الاتصال غير مستقر"}]},
  pt:{tap_lbl:"· Toque para Iniciar ·",c_eye:"Por favor leia a política de privacidade",c_sub:"Este app funciona completamente em local.<br>Sem servidores. Sem rastreamento.",c_chk:"Li a política de privacidade e concordo.",c_ok:"Iniciar",s_title:"CONFIGURAÇÕES",s_opt:"OPÇÕES",s_feat:"RECURSOS",h_ready:"PRONTO",h_scan:"ESCANEANDO",h_pause:"PAUSADO",ml_sig:"SINAL",ml_dl:"DOWNLOAD",ml_rtt:"LATÊNCIA",l_s:"FORTE",l_g:"BOA",l_m:"MÉDIA",l_w:"FRACA",btn_start:"Iniciar Scan",btn_stop:"Parar Scan",bd_current:"Conexão ativa",bd_main:"Dados reais",bd_est:"Estimado",bd_stability:"ESTABILIDADE",feats:["Tempo real via NetworkInformation API","Bolhas de rede interativas + AR","Intro cinemático 3.75s + jingle","10 idiomas disponíveis","Conforme GDPR · apenas local"],msgs:[{min:88,msg:"Sinal excelente — qualidade fibra"},{min:72,msg:"Sinal forte — conexão ideal"},{min:50,msg:"Bom sinal — estável e confiável"},{min:30,msg:"Sinal médio — suficiente"},{min:12,msg:"Sinal fraco — recepção limitada"},{min:0,msg:"Sinal crítico — conexão instável"}]},
  fr:{tap_lbl:"· Appuyer pour Démarrer ·",c_eye:"Veuillez lire la politique de confidentialité",c_sub:"Cette app fonctionne entièrement en local.<br>Pas de serveurs. Pas de suivi.",c_chk:"J'ai lu la politique de confidentialité et j'accepte.",c_ok:"Démarrer",s_title:"PARAMÈTRES",s_opt:"OPTIONS",s_feat:"FONCTIONNALITÉS",h_ready:"PRÊT",h_scan:"SCAN EN COURS",h_pause:"EN PAUSE",ml_sig:"SIGNAL",ml_dl:"TÉLÉCHARGEMENT",ml_rtt:"LATENCE",l_s:"FORT",l_g:"BON",l_m:"MOYEN",l_w:"FAIBLE",btn_start:"Démarrer le scan",btn_stop:"Arrêter le scan",bd_current:"Connexion active",bd_main:"Données réelles",bd_est:"Estimé",bd_stability:"STABILITÉ",feats:["Temps réel via NetworkInformation API","Bulles réseau interactives + AR","Intro cinématique 3.75s + jingle","10 langues disponibles","Conforme RGPD · local uniquement"],msgs:[{min:88,msg:"Signal excellent — qualité fibre"},{min:72,msg:"Signal fort — connexion optimale"},{min:50,msg:"Bon signal — stable et fiable"},{min:30,msg:"Signal moyen — suffisant"},{min:12,msg:"Signal faible — réception limitée"},{min:0,msg:"Signal critique — connexion instable"}]},
  ru:{tap_lbl:"· Нажмите для Запуска ·",c_eye:"Прочитайте политику конфиденциальности",c_sub:"Приложение работает полностью локально.<br>Без серверов. Без слежки.",c_chk:"Я прочитал(а) политику и согласен(на).",c_ok:"Начать",s_title:"НАСТРОЙКИ",s_opt:"ОПЦИИ",s_feat:"ФУНКЦИИ",h_ready:"ГОТОВ",h_scan:"СКАНИРОВАНИЕ",h_pause:"ПАУЗА",ml_sig:"СИГНАЛ",ml_dl:"ЗАГРУЗКА",ml_rtt:"ЗАДЕРЖКА",l_s:"СИЛЬНЫЙ",l_g:"ХОРОШИЙ",l_m:"СРЕДНИЙ",l_w:"СЛАБЫЙ",btn_start:"Начать сканирование",btn_stop:"Остановить сканирование",bd_current:"Активное соединение",bd_main:"Реальные данные",bd_est:"Оценочно",bd_stability:"СТАБИЛЬНОСТЬ",feats:["Реалтайм через NetworkInformation API","Интерактивные сетевые пузыри + AR","Кинематическое вступление 3.75с","10 языков интерфейса","Соответствие GDPR · только локально"],msgs:[{min:88,msg:"Отличный сигнал — качество волокна"},{min:72,msg:"Сильный сигнал — оптимальное соединение"},{min:50,msg:"Хороший сигнал — стабильный и надёжный"},{min:30,msg:"Средний сигнал — достаточно"},{min:12,msg:"Слабый сигнал — ограниченный приём"},{min:0,msg:"Критический сигнал — соединение нестабильно"}]},
  ja:{tap_lbl:"· タップして開始 ·",c_eye:"プライバシーポリシーをお読みください",c_sub:"このアプリは完全にローカルで動作します。<br>サーバーなし。トラッキングなし。",c_chk:"プライバシーポリシーを読み、同意します。",c_ok:"開始",s_title:"設定",s_opt:"オプション",s_feat:"機能一覧",h_ready:"準備完了",h_scan:"スキャン中",h_pause:"一時停止",ml_sig:"シグナル",ml_dl:"ダウンロード",ml_rtt:"遅延",l_s:"強",l_g:"良",l_m:"中",l_w:"弱",btn_start:"スキャン開始",btn_stop:"スキャン停止",bd_current:"アクティブな接続",bd_main:"実データ",bd_est:"推定値",bd_stability:"安定性",feats:["NetworkInformation APIによるリアルタイム","インタラクティブネットワークバブル + AR","3.75秒シネマティックイントロ","12言語対応","GDPR準拠 · ローカルのみ"],msgs:[{min:88,msg:"優れたシグナル — 光ファイバー品質"},{min:72,msg:"強いシグナル — 最適な接続"},{min:50,msg:"良好なシグナル — 安定・信頼性高"},{min:30,msg:"中程度のシグナル — 十分"},{min:12,msg:"弱いシグナル — 受信制限あり"},{min:0,msg:"クリティカルシグナル — 接続不安定"}]},
  hr:{tap_lbl:"· Dodirnite za Pokretanje ·",c_eye:"Molimo pročitajte Politiku privatnosti",c_sub:"Ova app radi potpuno lokalno.<br>Bez servera. Bez praćenja.",c_chk:"Pročitao/la sam Politiku privatnosti i slažem se.",c_ok:"Pokreni",s_title:"POSTAVKE",s_opt:"OPCIJE",s_feat:"FUNKCIJE",h_ready:"SPREMAN",h_scan:"SKENIRANJE",h_pause:"PAUZA",ml_sig:"SIGNAL",ml_dl:"PREUZIMANJE",ml_rtt:"LATENCIJA",l_s:"JAK",l_g:"DOBAR",l_m:"SREDNJI",l_w:"SLAB",btn_start:"Pokreni skeniranje",btn_stop:"Zaustavi skeniranje",bd_current:"Aktivna veza",bd_main:"Stvarni podaci",bd_est:"Procijenjeno",bd_stability:"STABILNOST",feats:["Stvarno vrijeme putem NetworkInformation API","Interaktivni mrežni mjehurići + AR","3.75s kinematski uvod + jingle","12 jezika dostupno","Sukladno GDPR-u · samo lokalno"],msgs:[{min:88,msg:"Izvrstan signal — kvaliteta optike"},{min:72,msg:"Jak signal — optimalna veza"},{min:50,msg:"Dobar signal — stabilan i pouzdan"},{min:30,msg:"Srednji signal — dovoljan"},{min:12,msg:"Slab signal — ograničen prijem"},{min:0,msg:"Kritičan signal — veza nestabilna"}]},
  sr:{tap_lbl:"· Додирните за Почетак ·",c_eye:"Молимо прочитајте Политику приватности",c_sub:"Ова апп ради потпуно локално.<br>Без сервера. Без праћења.",c_chk:"Прочитао/ла сам Политику приватности и слажем се.",c_ok:"Покрени",s_title:"ПОДЕШАВАЊА",s_opt:"ОПЦИЈЕ",s_feat:"ФУНКЦИЈЕ",h_ready:"СПРЕМАН",h_scan:"СКЕНИРАЊЕ",h_pause:"ПАУЗА",ml_sig:"СИГНАЛ",ml_dl:"ПРЕУЗИМАЊЕ",ml_rtt:"ЛАТЕНЦИЈА",l_s:"ЈАК",l_g:"ДОБАР",l_m:"СРЕДЊИ",l_w:"САБ",btn_start:"Покрени скенирање",btn_stop:"Заустави скенирање",bd_current:"Активна веза",bd_main:"Стварни подаци",bd_est:"Процењено",bd_stability:"СТАБИЛНОСТ",feats:["Реално време преко NetworkInformation API","Интерактивни мрежни мехурићи + AR","3.75с кинематски увод + џингл","12 језика доступно","Усклађено са GDPR-ом · само локално"],msgs:[{min:88,msg:"Одличан сигнал — квалитет оптике"},{min:72,msg:"Јак сигнал — оптимална веза"},{min:50,msg:"Добар сигнал — стабилан и поуздан"},{min:30,msg:"Средњи сигнал — довољан"},{min:12,msg:"Слаб сигнал — ограничен пријем"},{min:0,msg:"Критичан сигнал — веза нестабилна"}]}
};
var lang=localStorage.getItem('wps_lang')||'de', T=LANGS[lang];

function setLang(l){
  lang=l; localStorage.setItem('wps_lang',l); T=LANGS[l];
  var fmap={zh:"'Noto Sans SC'",ar:"'Noto Sans Arabic'",ja:"'Noto Sans JP'",hi:"'Noto Sans Devanagari'"};
  document.body.style.fontFamily=(fmap[l]||"'Space Grotesk'")+",sans-serif";
  document.body.dir=l==='ar'?'rtl':'ltr';
  applyLang();
}
function applyLang(){
  T=LANGS[lang];
  setText('c-eye',T.c_eye); setHTML('c-sub',T.c_sub); setText('c-chk',T.c_chk); setText('cta',T.c_ok);
  var cl=$('c-leg'); if(cl) cl.textContent=LEG[lang];
  setText('s-title',T.s_title); setText('s-opt',T.s_opt); setText('s-feat',T.s_feat);
  setText('ml-sig',T.ml_sig); setText('ml-dl',T.ml_dl); setText('ml-rtt',T.ml_rtt);
  setText('l-s',T.l_s); setText('l-g',T.l_g); setText('l-m',T.l_m); setText('l-w',T.l_w);
  var bi=$('badge-inner');
  if(bi) bi.textContent=S.scanning?T.h_scan:S.paused?T.h_pause:T.h_ready;
  setText('btn-lbl',S.scanning?T.btn_stop:T.btn_start);
  var fl=$('feat-list');
  if(fl){fl.innerHTML='';T.feats.forEach(function(f){var li=document.createElement('li');li.textContent=f;fl.appendChild(li);});}
  document.querySelectorAll('[data-lang]').forEach(function(b){b.classList.toggle('on',b.getAttribute('data-lang')===lang);});
  var tsl=$('tap-start-label'); if(tsl) tsl.textContent=T.tap_lbl||'· Tap to Start ·';
}
